#!/bin/bash

yum install epel-release -y
yum install nginx -y
export HOSTNAME=$(curl -s http://192.168.1.24/metadata/v1/hostname)
export PUBLIC_IPV4=$(curl -s http://192.168.1.24/metadata/v1/interfaces/public/0/ipv4/address)
echo Droplet: $HOSTNAME, IP Address: $PUBLIC_IPV4 > /usr/share/nginx/html/index.html
systemctl enable nginx
systemctl start nginx
